name: GitHub Actions Infra
run-name: ${{ github.actor }} is provisioing infra 🚀
on: 
 push:
   branches:
   - main
jobs:
  setup_servers:
    runs-on: ubuntu-latest   
    permissions:
            id-token: write
            contents: read
    steps:
      - name: Checkout the infra repository
        uses: actions/checkout@v2
      - name: Install Prerequisites
        run: |
          sudo apt-get update
          pip -V
          wget https://github.com/rebuy-de/aws-nuke/releases/download/v2.25.0/aws-nuke-v2.25.0-linux-amd64.tar.gz
          tar -xvf aws-nuke-v2.25.0-linux-amd64.tar.gz
          sudo mv aws-nuke-v2.25.0-linux-amd64 /usr/local/bin/aws-nuke
          ls -ltr /usr/local/bin/aws-nuke
        shell: bash  
      - name: dry run aws-nuke
        run:
          aws-nuke -c config/nuke-config.yml --access-key-id ${{ secrets.AWS_ACCESS_KEY_ID }} --secret-access-key ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
        shell: bash  
